### ISSUE TITLE
NameError: name 'SIGINT' is not defined

### ISSUE THREAD

**Issue by vmarrazzo** [karpierz/pcap-ct#6]
Hi 

My environment is 
- Ubuntu
- Python 3.9.5
- pcap-ct 1.2.3b5

When I execute below code

> pc = pcap.pcap(input_pcap_trace)
> [print(a) for a in pc]

I am obtaining below error message

> NameError: name 'SIGINT' is not defined

I have read that was available a fix for this bug, do you need help to test it on linux?

Regards

**Comment by karpierz** [comment]
Fixed in: pcap-ct 1.2.3b6
